from fastapi import FastAPI

from meteofrance import MeteoFrance


app=FastAPI()

# Créez une instance de la classe MeteoFrance avec votre clé API
meteo = MeteoFrance(api_key=eyJ4NXQiOiJZV0kxTTJZNE1qWTNOemsyTkRZeU5XTTRPV014TXpjek1UVmhNbU14T1RSa09ETXlOVEE0Tnc9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJsZmIuanVsaWVuQGNhcmJvbi5zdXBlciIsImFwcGxpY2F0aW9uIjp7Im93bmVyIjoibGZiLmp1bGllbiIsInRpZXJRdW90YVR5cGUiOm51bGwsInRpZXIiOiJVbmxpbWl0ZWQiLCJuYW1lIjoiRGVmYXVsdEFwcGxpY2F0aW9uIiwiaWQiOjEwOTQwLCJ1dWlkIjoiMzEzOTVmMTMtMjFiNy00ODIwLTg4MjctMjk2MjhhMTZmMDM1In0sImlzcyI6Imh0dHBzOlwvXC9wb3J0YWlsLWFwaS5tZXRlb2ZyYW5jZS5mcjo0NDNcL29hdXRoMlwvdG9rZW4iLCJ0aWVySW5mbyI6eyI1MFBlck1pbiI6eyJ0aWVyUXVvdGFUeXBlIjoicmVxdWVzdENvdW50IiwiZ3JhcGhRTE1heENvbXBsZXhpdHkiOjAsImdyYXBoUUxNYXhEZXB0aCI6MCwic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0Ijoic2VjIn19LCJrZXl0eXBlIjoiUFJPRFVDVElPTiIsInN1YnNjcmliZWRBUElzIjpbeyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6IkFST01FLVBJIiwiY29udGV4dCI6IlwvcHVibGljXC9hcm9tZXBpXC8xLjAiLCJwdWJsaXNoZXIiOiJhZG1pbl9tZiIsInZlcnNpb24iOiIxLjAiLCJzdWJzY3JpcHRpb25UaWVyIjoiNTBQZXJNaW4ifV0sInRva2VuX3R5cGUiOiJhcGlLZXkiLCJpYXQiOjE3MTA4NDY0MzAsImp0aSI6IjNkNjQyOTk4LTdmYzYtNGQ2OC1hNDQ0LTQ3ZDc3ZDlhYmJlMSJ9.AW8MKfIJvc6d6lmQ-EhEraxhomVwHrrrKB4ZXTbIWQ-J698rFxKbVkph-A5eCB-ImRrH0VWlkaC1UElGdKTcixiVsFDoEo0QBoc_cK-E7rlCN2kl9ZuEfULFw70BD6yxpMeWdDxEIG79KySHlPl4X_QL7hySLGlmCnWFNFNU5mlAVA0TmmaP2ZutT7bmVPq3_TZC34qai_O2Y3ExJFzp4Pw4PRTM2lJdY9C9xMfMhvQ8jVVPHicfj1BGfJPKdKl-YB2fgR93Noy0GIxqwwDS7zW8bkqKW9fETFZ5i24RFiTTG-SZ3nkqSCo8Lvo8sawsV-mqEU97uh3FOVhuNIYnog==)

# Obtenez les prévisions météorologiques pour une ville spécifique (par exemple Paris)
city_forecast = meteo.get_forecast(city="Paris")

# Affichez les prévisions météorologiques
print(city_forecast)






#  acces bdd 


# acces online data 
@app.get("/pull_data")
def pull_data(formulaire): 
   
    data="fetching"

    return data